spring:
  application:
    name: silingan
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:file:./data/silingan-db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true     # allow external connections (DBeaver / IntelliJ)

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        session_factory:
          statement_inspector: com.ria.olita.tech.silingan.config.CommunityStatementInspector
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  security:
    oauth2:
      client:
        registration:
          silingan:
            client-id: silingan-api
            client-secret: QJWjt2OugT9UK2hSjrDZQGRhv5IUQgH6
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/silingan
        provider:
          silingan:
            issuer-uri: http://localhost:8080/realms/silingan-platform
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/silingan-platform
          jwk-set-uri: http://localhost:8080/realms/silingan-platform/protocol/openid-connect/certs

keycloak:
  url: http://localhost:8080
  realm: silingan-platform
  client-id: silingan-backend
  client-secret: kxY6kRsvCejFAB4jwytOUH7mhkpbhyYN

server:
  port: 8082

logging:
  level:
    root: INFO
    com.ria.olita.tech.silingan.security: DEBUG
    org.springframework.security: DEBUG
