ALTER SCHEMA public OWNER TO keycloak;

GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

GRANT ALL ON SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO keycloak;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO keycloak;

ALTER DATABASE keycloak OWNER TO keycloak;